version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:root@db:3306/belajar_reactjs_contact_management
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_PATH: /api

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: belajar_reactjs_contact_management
    volumes:
      - mysql_data:/var/lib/mysql/
volumes:
  mysql_data:
